# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fpga1_deployment_sou_0_0/design_1_fpga1_deployment_sou_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fpga1_deployment_sou_0_0 || ORIG_REF_NAME==design_1_fpga1_deployment_sou_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fpga1_deployment_rec_0_0/design_1_fpga1_deployment_rec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fpga1_deployment_rec_0_0 || ORIG_REF_NAME==design_1_fpga1_deployment_rec_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_input_packet_0/design_1_input_packet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_input_packet_0 || ORIG_REF_NAME==design_1_input_packet_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_two_dimension_dct_0_0/design_1_two_dimension_dct_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_two_dimension_dct_0_0 || ORIG_REF_NAME==design_1_two_dimension_dct_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_quantizer_0_0/design_1_quantizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_quantizer_0_0 || ORIG_REF_NAME==design_1_quantizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zig_zag_0_0/design_1_zig_zag_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zig_zag_0_0 || ORIG_REF_NAME==design_1_zig_zag_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_run_length_encoder_0_0/design_1_run_length_encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_run_length_encoder_0_0 || ORIG_REF_NAME==design_1_run_length_encoder_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
