# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# XDC: new/constraints.xdc

# Block Designs: bd/canteloupe/canteloupe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe || ORIG_REF_NAME==canteloupe} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_microblaze_0_0/canteloupe_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_microblaze_0_0 || ORIG_REF_NAME==canteloupe_microblaze_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_dlmb_v10_0/canteloupe_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_dlmb_v10_0 || ORIG_REF_NAME==canteloupe_dlmb_v10_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_ilmb_v10_0/canteloupe_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_ilmb_v10_0 || ORIG_REF_NAME==canteloupe_ilmb_v10_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_dlmb_bram_if_cntlr_0/canteloupe_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==canteloupe_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_ilmb_bram_if_cntlr_0/canteloupe_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==canteloupe_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_lmb_bram_0/canteloupe_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_lmb_bram_0 || ORIG_REF_NAME==canteloupe_lmb_bram_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_xbar_0/canteloupe_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_xbar_0 || ORIG_REF_NAME==canteloupe_xbar_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_microblaze_0_axi_periph_0/canteloupe_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_microblaze_0_axi_periph_0 || ORIG_REF_NAME==canteloupe_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_microblaze_0_axi_intc_0/canteloupe_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_microblaze_0_axi_intc_0 || ORIG_REF_NAME==canteloupe_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_microblaze_0_xlconcat_0/canteloupe_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_microblaze_0_xlconcat_0 || ORIG_REF_NAME==canteloupe_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_mdm_1_0/canteloupe_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_mdm_1_0 || ORIG_REF_NAME==canteloupe_mdm_1_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_clk_wiz_1_0/canteloupe_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_clk_wiz_1_0 || ORIG_REF_NAME==canteloupe_clk_wiz_1_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_rst_clk_wiz_1_100M_0/canteloupe_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==canteloupe_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_axi_uartlite_0_0/canteloupe_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_axi_uartlite_0_0 || ORIG_REF_NAME==canteloupe_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_mig_7series_0_0/canteloupe_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_mig_7series_0_0 || ORIG_REF_NAME==canteloupe_mig_7series_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_rst_mig_7series_0_81M_0/canteloupe_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==canteloupe_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_axi_fifo_mm_s_0_0/canteloupe_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==canteloupe_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_xlconstant_0_0/canteloupe_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_xlconstant_0_0 || ORIG_REF_NAME==canteloupe_xlconstant_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_system_ila_0_0/canteloupe_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_system_ila_0_0 || ORIG_REF_NAME==canteloupe_system_ila_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_two_dimension_dct_0_0/canteloupe_two_dimension_dct_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_two_dimension_dct_0_0 || ORIG_REF_NAME==canteloupe_two_dimension_dct_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_quantizer_0_0/canteloupe_quantizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_quantizer_0_0 || ORIG_REF_NAME==canteloupe_quantizer_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_zig_zag_0_0/canteloupe_zig_zag_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_zig_zag_0_0 || ORIG_REF_NAME==canteloupe_zig_zag_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_run_length_encoder_0_0/canteloupe_run_length_encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_run_length_encoder_0_0 || ORIG_REF_NAME==canteloupe_run_length_encoder_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_frame_generator_cust_0_0/canteloupe_frame_generator_cust_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_frame_generator_cust_0_0 || ORIG_REF_NAME==canteloupe_frame_generator_cust_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/canteloupe_tri_mode_ethernet_ma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_tri_mode_ethernet_ma_1_0 || ORIG_REF_NAME==canteloupe_tri_mode_ethernet_ma_1_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_mii_to_rmii_0_0/canteloupe_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_mii_to_rmii_0_0 || ORIG_REF_NAME==canteloupe_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_us_0/canteloupe_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_us_0 || ORIG_REF_NAME==canteloupe_auto_us_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_us_1/canteloupe_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_us_1 || ORIG_REF_NAME==canteloupe_auto_us_1} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_ds_0/canteloupe_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_ds_0 || ORIG_REF_NAME==canteloupe_auto_ds_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_ds_1/canteloupe_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_ds_1 || ORIG_REF_NAME==canteloupe_auto_ds_1} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_cc_0/canteloupe_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_cc_0 || ORIG_REF_NAME==canteloupe_auto_cc_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_pc_0/canteloupe_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_pc_0 || ORIG_REF_NAME==canteloupe_auto_pc_0} -quiet] -quiet

# IP: bd/canteloupe/ip/canteloupe_auto_ds_2/canteloupe_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==canteloupe_auto_ds_2 || ORIG_REF_NAME==canteloupe_auto_ds_2} -quiet] -quiet

# XDC: bd/canteloupe/canteloupe_ooc.xdc
