# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_system_ila_0_1/canteloupe_system_ila_0_1.xci
# IP: The module: 'canteloupe_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_system_ila_0_1/bd_0/bd_1338.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1338 || ORIG_REF_NAME==bd_1338} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_system_ila_0_1/canteloupe_system_ila_0_1.xci
# IP: The module: 'canteloupe_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_system_ila_0_1/bd_0/bd_1338.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1338 || ORIG_REF_NAME==bd_1338} -quiet] -quiet
