# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/tri_mode_ethernet_mac_2.xci
# IP: The module: 'tri_mode_ethernet_mac_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/tri_mode_ethernet_mac_2.xci
# IP: The module: 'tri_mode_ethernet_mac_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhouyuf5/FPGA2_TEMAC/FPGA2_TEMAC.srcs/sources_1/ip/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
