set_property MARK_DEBUG true [get_nets {rmii2phy_txd_0_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {rmii2phy_txd_0_OBUF[1]}]
set_property MARK_DEBUG true [get_nets rmii2phy_tx_en_0_OBUF]
connect_debug_port u_ila_0/clk [get_nets [list canteloupe_i/tri_mode_ethernet_ma_0/inst/example_clocks/inst/refclk]]
connect_debug_port dbg_hub/clk [get_nets canteloupe_i/tri_mode_ethernet_ma_0/inst/gtx_clk_bufg]

connect_debug_port u_ila_0/clk [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/example_clocks/inst/refclk]]
connect_debug_port dbg_hub/clk [get_nets sys_clock_IBUF]


set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/rx_mic_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[7]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/rx_mic_TLAST]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/tx_fifo_TLAST]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/rx_mic_TREADY]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/rx_mic_TVALID]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/tx_fifo_TREADY]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/tx_fifo_TVALID]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/inst/mem/fifo_we]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0/inst/mem/mem_reg]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tlast]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tready]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tvalid]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[7]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[3]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_tx_en]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_tx_er]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tdata[7]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[7]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tlast]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tready]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_fifo_tvalid]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tlast]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tready]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tvalid]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[3]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_tx_en]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_tx_er]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_tx_en]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_tx_er]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[3]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_txd[3]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_tx_en]]
connect_debug_port u_ila_0/probe8 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_to_rmii/mac2rmii_tx_er]]

set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/frame_generator_cust_0_tx_fifo_TDATA[7]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0_tx_fifo_TLAST]
set_property MARK_DEBUG true [get_nets canteloupe_i/frame_generator_cust_0_tx_fifo_TVALID]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1_mii_tx_en]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1_mii_tx_er]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1_mii_txd[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1_mii_txd[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1_mii_txd[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1_mii_txd[3]}]

set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[7]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[8]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[3]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[4]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[5]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[0]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[1]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[2]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[6]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[7]}]
set_property MARK_DEBUG true [get_nets {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[8]}]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/wr_en]
set_property MARK_DEBUG true [get_nets canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/rd_en]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list canteloupe_i/clk_wiz_1/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[3]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[4]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[5]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[6]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[7]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/a_din[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list canteloupe_i/frame_generator_cust_0/tx_fifo_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/wr_en]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst/mii_interface/mii_tx_clk_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 9 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[3]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[4]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[5]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[6]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[7]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/b_dout[8]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/user_side_FIFO/tx_fifo_i/tx_ramgen_i/rd_en]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list canteloupe_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_txd[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 8 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[3]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[4]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[5]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[6]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tdata[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 4 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[0]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[1]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[2]} {canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_txd[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 8 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[0]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[1]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[2]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[3]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[4]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[5]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[6]} {canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tdata[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 8 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[0]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[1]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[2]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[3]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[4]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[5]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[6]} {canteloupe_i/frame_generator_cust_0/tx_fifo_TDATA[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list canteloupe_i/frame_generator_cust_0/inst/mem/fifo_we]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list canteloupe_i/frame_generator_cust_0/inst/mem/mem_reg]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
connect_debug_port u_ila_2/probe7 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_tx_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe8]
set_property port_width 1 [get_debug_ports u_ila_2/probe8]
connect_debug_port u_ila_2/probe8 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_tx_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe9]
set_property port_width 1 [get_debug_ports u_ila_2/probe9]
connect_debug_port u_ila_2/probe9 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/trimac_sup_block/mii_tx_er]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe10]
set_property port_width 1 [get_debug_ports u_ila_2/probe10]
connect_debug_port u_ila_2/probe10 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/mii_tx_er]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe11]
set_property port_width 1 [get_debug_ports u_ila_2/probe11]
connect_debug_port u_ila_2/probe11 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tlast]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe12]
set_property port_width 1 [get_debug_ports u_ila_2/probe12]
connect_debug_port u_ila_2/probe12 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/tx_axis_fifo_tvalid]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe13]
set_property port_width 1 [get_debug_ports u_ila_2/probe13]
connect_debug_port u_ila_2/probe13 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tlast]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe14]
set_property port_width 1 [get_debug_ports u_ila_2/probe14]
connect_debug_port u_ila_2/probe14 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tready]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe15]
set_property port_width 1 [get_debug_ports u_ila_2/probe15]
connect_debug_port u_ila_2/probe15 [get_nets [list canteloupe_i/tri_mode_ethernet_ma_1/inst/trimac_fifo_block/tx_axis_mac_tvalid]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe16]
set_property port_width 1 [get_debug_ports u_ila_2/probe16]
connect_debug_port u_ila_2/probe16 [get_nets [list canteloupe_i/frame_generator_cust_0/tx_fifo_TLAST]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe17]
set_property port_width 1 [get_debug_ports u_ila_2/probe17]
connect_debug_port u_ila_2/probe17 [get_nets [list canteloupe_i/frame_generator_cust_0/tx_fifo_TVALID]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list canteloupe_i/clk_wiz_1/inst/clk_out4]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 2 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {rmii2phy_txd_0_OBUF[0]} {rmii2phy_txd_0_OBUF[1]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property port_width 1 [get_debug_ports u_ila_3/probe1]
connect_debug_port u_ila_3/probe1 [get_nets [list rmii2phy_tx_en_0_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
