# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/canteloupe_tri_mode_ethernet_ma_1_0.xci
# IP: The module: 'canteloupe_tri_mode_ethernet_ma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/tri_mode_ethernet_mac_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/vio_0/vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/mii_to_rmii_0/mii_to_rmii_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mii_to_rmii_0 || ORIG_REF_NAME==mii_to_rmii_0} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_ooc.xdc

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/vio_0/vio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/mii_to_rmii_0/mii_to_rmii_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mii_to_rmii_0 || ORIG_REF_NAME==mii_to_rmii_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/canteloupe_tri_mode_ethernet_ma_1_0.xci
# IP: The module: 'canteloupe_tri_mode_ethernet_ma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/tri_mode_ethernet_mac_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/vio_0/vio_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/mii_to_rmii_0/mii_to_rmii_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mii_to_rmii_0 || ORIG_REF_NAME==mii_to_rmii_0} -quiet] -quiet

# IP: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_ooc.xdc

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/tri_mode_ethernet_mac_2/synth/tri_mode_ethernet_mac_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_2 || ORIG_REF_NAME==tri_mode_ethernet_mac_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/vio_0/vio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/mii_to_rmii_0/mii_to_rmii_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mii_to_rmii_0 || ORIG_REF_NAME==mii_to_rmii_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/poyisamu/fifoStream/fifoStream.srcs/sources_1/bd/canteloupe/ip/canteloupe_tri_mode_ethernet_ma_1_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
